config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  root "events#index"

  get "/attend_events/:event_id", to: "attend_events#destroy"
  get "/attend_events/", to: "attend_events#add"
  get "/users/:id", to: "users#show"

  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'

  has_many :event_attendees, foreign_key: "event_id", dependent: :destroy
  has_many :attendees, through: :event_attendees, dependent: :destroy

  validates :title, presence: true, length: { minimum: 5 }
  validates :description, presence: true    
  validates :date, presence: true
  validates :time, presence: true    
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :event, class_name: 'Event'
  belongs_to :attendee, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: "creator_id", class_name: "Event"

  has_many :event_attendees, foreign_key: "attendee_id", dependent: :destroy
  has_many :attended_events, through: :event_attendees, source: :event, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attend_events_controller.rb
class AttendEventsController < ApplicationController
  before_action :authenticate_user!

  def add    
    @attend = EventAttendee.new(attend_params)

    if current_user.attended_event_ids.include?(attend_params[:event_id].to_i)
      flash.notice = "Already signed up for this event!"        
    elsif @attend.save
      flash.notice = "Signed up for event!"
    else 
      flash.notice = "Error signing up for event!"
    end
    redirect_to root_path
  end
  
  def destroy
    flash.notice = "You were removed from event!"
    EventAttendee.where(event_id: params[:event_id].to_i, attendee_id: current_user.id.to_i).delete_all
    redirect_to root_path
  end

  private

  def attend_params
    params.permit(:attendee_id, :event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create 
    @event = current_user.events.new(event_params)

    if @event.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    EventAttendee.where(event_id: params[:id].to_i).delete_all
    @event.destroy

    redirect_to root_path, status: :see_other
  end


  private 

  def event_params
    params.require(:event).permit(:title, :description, :date, :time)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @events = @user.events
    @attended_events = attended_events_without_users
  end

  private

  def attended_events_without_users
    @user.attended_events.where.not(creator_id: @user.id.to_i)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<h1>Edit event</h1>
<%= form_with model: @event do |form| %>
    <% if @event.errors.any? %>
        <ul>
            <% @event.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    <% end %>

    <div>
        <%= form.label :title %> <br>
        <%= form.text_field :title, autofocus: true %>
    </div>
    <div>
        <%= form.label :description %><br>
        <%= form.text_area :description %>
    </div>
    <div>
        <%= form.label :date %> <br>
        <%= form.date_field :date %>
    </div>
    <div>
        <%= form.label :time %><br>
        <%= form.time_field :time %>
    </div>
    <%= form.submit "Edit event", class: "save-btn" %>
    <div class="delete-btn">
        <%= link_to "Delete event", event_path(@event), data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure?"
                      } %>
    </div>
<% end %>

app/views/events/index.html.erb
<h1>EVENTS</h1>
<div class="events-container">
    <% @events.each do |event| %>
        <div class="event-container" >
            <p class="title"><%= event.title %></p>
            <p>Date: <%= event.date %></p>
            <p>Time: <%= event.time.hour %>:<%= event.time.min %></p>
            <p>People going: <%= event.attendees.count %></p>
            <p class="creator-link">Creator:
            <%= link_to controller: "users", action: "show", id: event.creator.id do %>
                <%= event.creator.username %>
            <% end %>
            </p>
            <%= link_to "", controller: "events", action: "show", id: event.id %>
        </div>
    <% end %>
</div>

app/views/events/new.html.erb
<h1>Create new event</h1>
<%= form_with model: @event do |form| %>
    <% if @event.errors.any? %>
        <ul >
            <% @event.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    <% end %>

    <div>
        <%= form.label :title %> <br>
        <%= form.text_field :title, autofocus: true %>
    </div>
    <div>
        <%= form.label :description %> <br>
        <%= form.text_area :description %>
    </div>
    <div>
        <%= form.label :date %> <br>
        <%= form.date_field :date %>
    </div>
    <div>
        <%= form.label :time %> <br>
        <%= form.time_field :time %>
    </div>
    <%= form.submit "Create event", class: "save-btn" %>
<% end %>

app/views/events/show.html.erb
<div class="profile-container">
    <h1><%= @event.title %></h1>
    <div>
        <% if user_signed_in?%>
        <% if @event.creator_id == current_user.id%>
            <%= link_to "Edit event", edit_event_path, class: "edit-btn" %>
        <% end %>
        <% end %>
    </div>
    <p class="description"><%= @event.description %></p>
    <p>Date: <%= @event.date %></p>
    <p>Time: <%= @event.time.hour %>:<%= @event.time.min %></p>
    <p class="creator-link">Creator:
    <%= link_to controller: "users", action: "show", id: @event.creator.id do %> 
        <%= @event.creator.username %>
    <% end %>
    </p>
    <p>People going: <%= @event.attendees.count %></p>
    <p>List of people who are going:</p>
    <ul class="attendee-list">
        <% @event.attendees.each do |attendee| %>
            <%= link_to controller: "users", action: "show", id: attendee.id do %> 
                <li><%= attendee.username %></li>
            <% end %>
        <% end %>
    </ul>
    <% if user_signed_in? %>
        <% if @event.attendee_ids.include?(current_user.id) %>
            <div class="delete-btn">
                <%= link_to "Remove yourself from event", controller: "attend_events", action: "destroy", event_id: @event.id %>
            </div>
        <% else %>
            <div class="save-btn">
                <%= link_to "Attend", controller: "attend_events", action: "add" , attendee_id: current_user.id, event_id: @event.id %> 
            </div>
        <% end %>
    <% end %>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
    <h4>© 2023 Private events page</h4>
</div>

app/views/layouts/_navbar.html.erb
<div class='navbar'>
      <% if user_signed_in? %>
        <div>
            <%= link_to "Home", root_path %>
            <%= link_to "Create new event", new_event_path %>
        </div>
        <div>
            <div>Logged in as <%= current_user.username %></div>
            <%= link_to "Profile", controller: "/users", action: "show", id: current_user.id %>
            <%= link_to("Log out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete }) %>
        </div>
      <% else %>
            <div><%= link_to "Home", root_path %></div>
            <div>
              <%= link_to "Log In", new_user_session_path %>
              <%= link_to "Sign Up", new_user_registration_path %>
            </div>
      <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="flash-messages">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

    <div class="content-container" ><%= yield %></div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/show.html.erb
<div class="user-profile-container">
    <h1><%= @user.username %></h1>
    <h1>Contact: <%= @user.email %></h1>
    <% if @user == current_user %>
        <%= link_to "Edit profile", edit_user_registration_path, class: "edit-btn" %>
    <% end %>
    <% if @events.any? %>
        <p>Events <%= @user.username%> created:</p>
        <div class="events-container">
            <% @events.each do |event| %>
                <div class="event-container" >
                    <p class="title"><%= event.title %></p>
                    <p>Date: <%= event.date %></p>
                    <p>Time: <%= event.time.hour %>:<%= event.time.min %></p>
                    <p>People going: <%= event.attendees.count %></p>
                    <%= link_to "", controller: "events", action: "show", id: event.id %>
                </div>
            <% end %>
        </div>
    <% end %>
    <% if @attended_events.any? %>
        <p>Attended events:</p>
        <div class="events-container">
            
            <% @attended_events.each do |event| %>
                <div class="event-container" >
                        <p class="title"><%= event.title %></p>
                        <p>Date: <%= event.date %></p>
                        <p>Time: <%= event.time.hour %>:<%= event.time.min %></p>
                        <p>People going: <%= event.attendees.count %></p>
                        <p class="creator-link">Creator:
            <%= link_to controller: "users", action: "show", id: event.creator.id do %>
                <%= event.creator.username %>
            <% end %>
            </p>
                        <%= link_to "", controller: "events", action: "show", id: event.id %>
                    </div>
            <% end %>
        </div>
    <% end %>
</div>